### ISSUE TITLE
[Question] Are you planning to publish the infos / scripts?

### ISSUE THREAD

**Issue by 0xphk** [kmille/evil-maid-attack-on-encrypted-boot#1]
Thanks for the great talk!

As the title says, are you planning to release the infos and shell/python scripts used in your talk?
Would love to look into it as I try to fix something annoying during stage 1.5 decryption in the boot.img.

If grub is installed to SSD, the prompt for the key is always shown in old plain 80x25 output,
but when installed to a thumb drive to boot and unlock the disk, 
it respects the full resolution and I really want to know why this odd behavior is happening.

**Comment by kmille** [comment]
I'm working on it. I think I will publish it in the next few days.

**Comment by kmille** [comment]
done
